/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Authenticator SVC
 * API docs
 */

export interface UserInfoOut {
  email?: string;
  familyName?: string;
  givenName?: string;
  preferredUsername?: string;
  sub?: string;
}
