FROM node:18-alpine3.18 AS builder

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx:1.25.1-alpine AS prod

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --chmod=0755 ./docker/init-scripts/ /docker-entrypoint.d/

EXPOSE 80

WORKDIR /usr/share/nginx/html

ARG APP_NAME 
ARG APP_VERSION

ENV VITE_APP_NAME=$APP_NAME
ENV VITE_APP_VERSION=$APP_VERSION