/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Authenticator SVC
 * API docs
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { OutError, OutUserLookup } from ".././models";
import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Returns a list of users that are currently online
 * @summary Get currently online users
 */
export const getOnlineUsers = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OutUserLookup[]>(
    { url: `/api/auth/user/online`, method: "GET", signal },
    options,
  );
};

export const getGetOnlineUsersQueryKey = () => {
  return [`/api/auth/user/online`] as const;
};

export const getGetOnlineUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getOnlineUsers>>,
  TError = ErrorType<OutError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnlineUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOnlineUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnlineUsers>>> = ({
    signal,
  }) => getOnlineUsers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOnlineUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetOnlineUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOnlineUsers>>
>;
export type GetOnlineUsersQueryError = ErrorType<OutError>;

export function useGetOnlineUsers<
  TData = Awaited<ReturnType<typeof getOnlineUsers>>,
  TError = ErrorType<OutError>,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnlineUsers>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getOnlineUsers>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetOnlineUsers<
  TData = Awaited<ReturnType<typeof getOnlineUsers>>,
  TError = ErrorType<OutError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnlineUsers>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getOnlineUsers>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetOnlineUsers<
  TData = Awaited<ReturnType<typeof getOnlineUsers>>,
  TError = ErrorType<OutError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnlineUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get currently online users
 */

export function useGetOnlineUsers<
  TData = Awaited<ReturnType<typeof getOnlineUsers>>,
  TError = ErrorType<OutError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOnlineUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetOnlineUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
