/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateLobby {
  description: string;
  /**
   * @minimum 2
   * @maximum 10
   */
  maxPlayers: number;
  name: string;
}
