/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OutLobby {
  createdAt: string;
  currentPlayers: number;
  description: string;
  id: string;
  maxPlayers: number;
  name: string;
  owner: string;
}
